pipeline {
    agent any
    
    stages {
        stage('Checkout Code') {
            steps {
                // Clones the code from the Git repository
                git branch: 'main', url: 'https://github.com/shreshthr/Banking-System.git'
            }
        }
        
        stage('Build') {
            steps {
                // Navigate to BankingSystem directory and run the Gradle build command
                dir('BankingSystem') {
                    bat 'gradlew.bat clean build'
                }
            }
        }
        
        stage('Test') {
            steps {
                // Navigate to BankingSystem directory and run the Gradle test command
                dir('BankingSystem') {
                    bat 'gradlew.bat test'
                }
            }
        }
    }
    
    post {
        always {
            // Archive JAR files or other build artifacts
            archiveArtifacts artifacts: 'BankingSystem/build/libs/*.jar', allowEmptyArchive: true
            
            // Publish JUnit test results for test reporting
            junit 'BankingSystem/build/test-results/test/*.xml'
        }
    }
}

