pipeline {
    agent any
    
    stages {
        stage('Checkout Code') {
            steps {
                // Clones the code from the Git repository
                git branch: 'main', url: 'https://github.com/shreshthr/Banking-System.git'
            }
        }
        
        stage('Build') {
            steps {
                // Run the Gradle build using the current directory reference
                dir('BankingSystem') {
                    bat 'C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\BankingSystemProject\\gradlew.bat clean build'
                }
            }
        }
        
        stage('Test') {
            steps {
                // Run the Gradle tests
                dir('BankingSystem') {
                    bat 'C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\BankingSystemProject\\gradlew.bat test'
                }
            }
        }
    }
    
}

